Repository dnd-side-project/dnd-12th-9-frontend, pull requests merged in 2025-02, with the labels that each got.

#10 [CHORE] tailwind 관련 클래스 병합 유틸리티 추가
  packages/ui/package.json
  packages/ui/src/lib/core.ts
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: chore

#13 [FEAT] Typography mdx 문서, Text 컴포넌트 구현
  .gitignore
  apps/storybook/globals.css
  apps/storybook/stories/Text.stories.tsx
  apps/storybook/stories/Typography.mdx
  apps/web/app/layout.tsx
  apps/web/package.json
  apps/web/public/font/PretendardVariable.woff2
  apps/web/tailwind.config.ts
  packages/ui/src/components/Text/Text.tsx
  packages/ui/src/components/Text/index.ts
  packages/ui/src/components/index.ts
  pnpm-lock.yaml
Labels: feat

#15 [FEAT] 헤더 컴포넌트 구현
  apps/storybook/stories/Header.stories.tsx
  apps/storybook/stories/IconButton.stories.tsx
  packages/ui/src/components/Box/Box.tsx
  packages/ui/src/components/Box/index.tsx
  packages/ui/src/components/Center/Center.tsx
  packages/ui/src/components/Center/index.tsx
  packages/ui/src/components/Header/Header.tsx
  packages/ui/src/components/Header/HeaderElement.tsx
  packages/ui/src/components/Header/index.ts
  packages/ui/src/components/IconButton/IconButton.tsx
  packages/ui/src/components/IconButton/index.ts
  packages/ui/src/components/index.ts
  packages/ui/src/polymorphics.ts
Labels: feat

#22 [FEAT] assets설정, Icon 컴포넌트 구현
  apps/storybook/stories/Icon.stories.tsx
  apps/web/next.config.mjs
  packages/ui/package.json
  packages/ui/src/components/Icon/Icon.tsx
  packages/ui/src/components/Icon/assets/back.tsx
  packages/ui/src/components/Icon/assets/bag.tsx
  packages/ui/src/components/Icon/assets/book.tsx
  packages/ui/src/components/Icon/assets/camera.tsx
  packages/ui/src/components/Icon/assets/close.tsx
  packages/ui/src/components/Icon/assets/cryGhost.tsx
  packages/ui/src/components/Icon/assets/delete.tsx
  packages/ui/src/components/Icon/assets/down.tsx
  packages/ui/src/components/Icon/assets/download.tsx
  packages/ui/src/components/Icon/assets/edit.tsx
  packages/ui/src/components/Icon/assets/exclamation.tsx
  packages/ui/src/components/Icon/assets/heart.tsx
  packages/ui/src/components/Icon/assets/home.tsx
  packages/ui/src/components/Icon/assets/index.ts
  packages/ui/src/components/Icon/assets/info.tsx
  packages/ui/src/components/Icon/assets/kebab.tsx
  packages/ui/src/components/Icon/assets/link.tsx
  packages/ui/src/components/Icon/assets/logo.tsx
  packages/ui/src/components/Icon/assets/menu.tsx
  packages/ui/src/components/Icon/assets/next.tsx
  packages/ui/src/components/Icon/assets/note.tsx
  packages/ui/src/components/Icon/assets/plus.tsx
  packages/ui/src/components/Icon/assets/remove.tsx
  packages/ui/src/components/Icon/assets/search.tsx
  packages/ui/src/components/Icon/assets/setting.tsx
  packages/ui/src/components/Icon/assets/share.tsx
  packages/ui/src/components/Icon/assets/shop.tsx
  packages/ui/src/components/Icon/assets/undo.tsx
  packages/ui/src/components/Icon/index.tsx
  packages/ui/src/components/index.ts
  pnpm-lock.yaml
  public/assets/blacky-done.png
  public/assets/blacky-ing.png
  public/assets/blacky-prev.png
  public/assets/cat-ghost-logo.png
  public/assets/closet.png
  public/assets/mission.png
  public/assets/share.png
  public/assets/store.png
Labels: feat, set

#21 [FEAT] color 토큰 추가
  packages/tailwind-config/tailwind.config.ts
  packages/tailwind-config/token.ts
Labels: feat

#26 [FEAT] Drawer 컴포넌트 구현
  apps/web/app/layout.tsx
  packages/ui/src/components/Drawer/Drawer.tsx
  packages/ui/src/components/Drawer/index.ts
  packages/ui/src/components/index.ts
  packages/ui/src/lib/motions.ts
Labels: feat

#27 [FEAT] TextField 컴포넌트/스토리북 구현, Icon 컴포넌트 Props 추가
  apps/storybook/stories/Icon.stories.tsx
  apps/storybook/stories/TextField.stories.tsx
  packages/ui/src/components/Icon/Icon.tsx
  packages/ui/src/components/Icon/assets/index.ts
  packages/ui/src/components/TextField/TextField.tsx
  packages/ui/src/components/TextField/index.ts
  packages/ui/src/components/index.ts
  packages/ui/src/hooks/useTextFieldValidation.ts
Labels: feat

#31 [FEAT] SearchBar 컴포넌트, 스토리북 구현
  apps/storybook/globals.css
  apps/storybook/stories/Icon.stories.tsx
  apps/storybook/stories/SearchBar.stories.tsx
  packages/ui/src/components/Icon/Icon.tsx
  packages/ui/src/components/Icon/assets/index.ts
  packages/ui/src/components/SearchBar/SearchBar.tsx
  packages/ui/src/components/SearchBar/index.ts
  packages/ui/src/components/index.ts
Labels: feat

#32 [FEAT] 버튼 컴포넌트
  apps/storybook/stories/Button.stories.tsx
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Button/assets/OrbIcon.tsx
  packages/ui/src/components/Button/index.ts
  packages/ui/src/components/Icon/assets/index.ts
Labels: feat

#34 [REFACTOR] icon color 객체 키 리팩토링
  apps/storybook/stories/Icon.stories.tsx
  packages/ui/src/components/Icon/Icon.tsx
  packages/ui/src/components/Icon/assets/index.ts
Labels: refactor

#35 [FEAT] Chip 컴포넌트,스토리북 구현
  apps/storybook/.storybook/main.ts
  apps/storybook/stories/Chip.stories.tsx
  packages/ui/src/components/Chip/Chip.tsx
  packages/ui/src/components/Chip/index.ts
  packages/ui/src/components/index.ts
Labels: feat

#40 [FEAT] 미션 페이지 UI 추가
  apps/web/app/_components/BackButton.tsx
  apps/web/app/components/.gitkeep
  apps/web/app/layout.tsx
  apps/web/app/mission/_components/MissionCard.tsx
  apps/web/app/mission/_components/MissionCardList.tsx
  apps/web/app/mission/page.tsx
  package.json
  packages/ui/src/components/Header/Header.tsx
  packages/ui/src/components/Header/HeaderElement.tsx
  packages/ui/src/components/Icon/assets/index.ts
  packages/ui/src/components/Icon/assets/missionCard.tsx
  packages/ui/src/components/Icon/assets/orb.tsx
  packages/ui/src/components/Layout/PageLayout/PageLayout.tsx
  packages/ui/src/components/Layout/PageLayout/index.ts
  packages/ui/src/components/Layout/index.ts
  packages/ui/src/components/index.ts
Labels: feat

#45 [BUGFIX] Chip 컴포넌트 outline -> ring 수정
  apps/storybook/stories/Chip.stories.tsx
  apps/web/app/page.tsx
  packages/ui/src/components/Chip/Chip.tsx
Labels: fix

#50 [FEAT] 스토어 페이지 UI
  apps/web/app/search/_components/BookCard.tsx
  apps/web/app/search/_components/BookStatusModal.tsx
  apps/web/app/search/_types/book.ts
  apps/web/app/search/page.tsx
  apps/web/app/store/_components/ItemBox.tsx
  apps/web/app/store/_components/StoreCard.tsx
  apps/web/app/store/constants/motions.ts
  apps/web/app/store/page.tsx
  apps/web/package.json
  apps/web/public/.gitkeep
  apps/web/public/BASIC_GHOST.png
  apps/web/public/STORE.png
  pnpm-lock.yaml
  public/assets/store.png
Labels: feat

#52 [FEAT] chip에서 사용하는 assets 추가
  apps/web/public/BEAUTIFUL_SENTENCE.png
  apps/web/public/BORING.png
  apps/web/public/DIFFICULT_SENTENCE.png
  apps/web/public/DISAPPOINTING.png
  apps/web/public/EASY_TO_READ.png
  apps/web/public/EMOTIONAL.png
  apps/web/public/IMMERSIVE.png
  apps/web/public/INFORMATIVE.png
  apps/web/public/KNOWLEDGEABLE.png
  apps/web/public/LACK_OF_COHERENCE.png
  apps/web/public/LONG_LASTING_AFTERGLOW.png
  apps/web/public/RECOMMENDABLE.png
  apps/web/public/STIMULATE_DOPAMINE.png
  apps/web/public/THREADBARE.png
Labels: feat

#46 feat: 카카오 로그인
  apps/web/app/auth/callback/route.ts
  apps/web/app/login/page.tsx
Labels: feat

#59 [FEAT] 로그인 작업 기타 처리, ky instance 설정
  apps/web/app/_api/auth.ts
  apps/web/app/_api/fetcher.ts
  apps/web/app/api/.gitkeep
  apps/web/app/auth/callback/route.ts
  apps/web/app/login/page.tsx
  apps/web/middleware.ts
  apps/web/package.json
  packages/api/package.json
  packages/api/src/.gitkeep
  packages/api/tsconfig.json
  pnpm-lock.yaml
  turbo.json
Labels: feat

#63 [FEAT] 카카오 로그인 페이지 ui
  apps/web/app/login/assets/KakaoLogo.tsx
  apps/web/app/login/assets/LoginCharacter.tsx
  apps/web/app/login/assets/LoginLogo.tsx
  apps/web/app/login/page.tsx
  apps/web/public/GHOST_COUCH.svg
Labels: feat

#64 [FEAT] 홈페이지 UI
  apps/web/app/_hooks/useFunnel.tsx
  apps/web/app/home/_components/Bubble.tsx
  apps/web/app/home/_components/Ghost.tsx
  apps/web/app/home/_components/HomeDrawer.tsx
  apps/web/app/home/_components/Summary.tsx
  apps/web/app/home/_components/TopBarButton.tsx
  apps/web/app/home/_constants/motions.ts
  apps/web/app/home/_constants/topbar.ts
  apps/web/app/home/page.tsx
  apps/web/app/onboarding/page.tsx
  apps/web/public/Chip/BEAUTIFUL_SENTENCE.png
  apps/web/public/Chip/BORING.png
  apps/web/public/Chip/DIFFICULT_SENTENCE.png
  apps/web/public/Chip/DISAPPOINTING.png
  apps/web/public/Chip/EASY_TO_READ.png
  apps/web/public/Chip/EMOTIONAL.png
  apps/web/public/Chip/IMMERSIVE.png
  apps/web/public/Chip/INFORMATIVE.png
  apps/web/public/Chip/KNOWLEDGEABLE.png
  apps/web/public/Chip/LACK_OF_COHERENCE.png
  apps/web/public/Chip/LONG_LASTING_AFTERGLOW.png
  apps/web/public/Chip/RECOMMENDABLE.png
  apps/web/public/Chip/STIMULATE_DOPAMINE.png
  apps/web/public/Chip/THREADBARE.png
  apps/web/public/Ghost/BASIC_GHOST.png
  apps/web/public/HOME.png
  apps/web/public/TopBar/CLOSET.png
  apps/web/public/TopBar/MISSION.png
  apps/web/public/TopBar/SHARE.png
  apps/web/public/TopBar/STORE.png
  packages/ui/src/components/Drawer/Drawer.tsx
  packages/ui/src/components/Icon/assets/index.ts
  packages/ui/src/components/Icon/assets/kakao.tsx
  packages/ui/src/components/Icon/assets/logo.tsx
Labels: feat

#67 [FEAT] 꾸미기 페이지 UI
  apps/web/app/_util/keys.ts
  apps/web/app/closet/_components/ItemCard.tsx
  apps/web/app/closet/_fixture/item.tsx
  apps/web/app/closet/_util/image.ts
  apps/web/app/closet/page.tsx
  apps/web/public/Ghost/BAEKDO_CAT_GHOST.png
  apps/web/public/Ghost/CAT_GHOST.png
  apps/web/public/Ghost/CHEESE_CAT_GHOST.png
  apps/web/public/Ghost/DETECTIVE_GHOST.png
  apps/web/public/Ghost/FRANKENSTEIN_GHOST.png
  apps/web/public/Ghost/LITTLEPRINCE_GHOST.png
  apps/web/public/Ghost/MUMMY_GHOST.png
  apps/web/public/Ghost/REDHOOD_GHOST.png
  apps/web/public/Ghost/SIAMESE_CAT_GHOST.png
  apps/web/public/Ghost/WIZARD_GHOST.png
  apps/web/public/closet/BG_CLOSET.png
  packages/ui/src/components/Layout/PageLayout/PageLayout.tsx
Labels: feat

#68 [FEAT] 평가 페이지 ui
  apps/web/app/books/[id]/review/_components/ReviewContent.tsx
  apps/web/app/books/[id]/review/_constants/keyword.ts
  apps/web/app/books/[id]/review/_util/keyword.ts
  apps/web/app/books/[id]/review/page.tsx
Labels: feat

#70 [FEAT] 닉네임 설정 페이지 ui 추가
  apps/web/app/nickname/page.tsx
  packages/ui/src/components/TextField/TextField.tsx
Labels: feat

#81 [FEAT] PC일때 회색 배경색 추가
  apps/web/app/books/page.tsx
  apps/web/app/layout.tsx
  packages/tailwind-config/tailwind.config.ts
Labels: feat

#85 [FEAT] 닉네임 설정 페이지 api 연동
  apps/web/app/_api/auth.ts
  apps/web/app/_api/mutations/useNickname.ts
  apps/web/app/auth/callback/route.ts
  apps/web/app/nickname/page.tsx
Labels: feat

#87 [FEAT] 스토어 페이지 API 연결
  apps/web/app/_api/mutations/useItemDraw.ts
  apps/web/app/_api/queries/index.ts
  apps/web/app/_api/queries/useMemberPoint.ts
  apps/web/app/_api/queryKey.ts
  apps/web/app/_api/types/book.ts
  apps/web/app/_api/types/common.ts
  apps/web/app/_api/types/draw.ts
  apps/web/app/_api/types/member.ts
  apps/web/app/_components/ItemModal.tsx
  apps/web/app/_components/RewardModal.tsx
  apps/web/app/_constants/reward.ts
  apps/web/app/home/page.tsx
  apps/web/app/store/_components/ItemBox.tsx
  apps/web/app/store/_components/ItemInfo.tsx
  apps/web/app/store/_components/StoreCard.tsx
  apps/web/app/store/constants/ghost.ts
  apps/web/app/store/constants/motions.ts
  apps/web/app/store/page.tsx
  packages/ui/src/components/Modal/Modal.tsx
  packages/ui/src/components/Modal/ModalContent.tsx
Labels: feat

#88 [FEAT] 꾸미기 페이지 api 연동
  apps/web/app/_api/fetcher.ts
  apps/web/app/_api/mutations/useUpdateEquippedItem.ts
  apps/web/app/_api/queries/item.ts
  apps/web/app/_api/types/item.ts
  apps/web/app/_api/types/response.ts
  apps/web/app/closet/_components/ClosetSecion.tsx
  apps/web/app/closet/_constants/item.tsx
  apps/web/app/closet/_hooks/useGhost.tsx
  apps/web/app/closet/page.tsx
Labels: feat

#91 chore: vercel speed insights 추가
  apps/web/app/layout.tsx
  apps/web/package.json
  pnpm-lock.yaml
Labels: chore

#89 [FEAT] 책장 페이지 api 연동
  apps/web/app/_api/mutations/useUpdateBook.ts
  apps/web/app/_api/queries/book.ts
  apps/web/app/_api/types/book.ts
  apps/web/app/_constants/status.ts
  apps/web/app/_util/queryClient.ts
  apps/web/app/books/[id]/_components/BookInfo.tsx
  apps/web/app/books/[id]/_components/BookStatusModal.tsx
  apps/web/app/books/[id]/_components/DetailSection.tsx
  apps/web/app/books/[id]/_components/DialogTrigger.tsx
  apps/web/app/books/[id]/_components/KeywordSection.tsx
  apps/web/app/books/[id]/_components/ReadingCard.tsx
  apps/web/app/books/[id]/page.tsx
  apps/web/app/books/_components/BookList.tsx
  apps/web/app/books/_components/CardList.tsx
  apps/web/app/books/_utils/getFilterBySearchParams.ts
  apps/web/app/books/page.tsx
  apps/web/app/search/_components/BookList.tsx
  apps/web/app/search/page.tsx
Labels: feat

#95 [FEAT] 자랑하기 페이지 UI
  apps/web/app/profile/_components/BottomButton.tsx
  apps/web/app/profile/_components/Card.tsx
  apps/web/app/profile/_components/Profile.tsx
  apps/web/app/profile/page.tsx
Labels: feat

#97 [FEAT] 튜토리얼 모달 연결
  apps/web/app/home/_components/Home.tsx
  apps/web/app/home/_components/OnBoardingCompleteModal.tsx
  apps/web/app/onboarding/page.tsx
Labels: feat

#96 [FEAT] 평가 페이지 api 추가
  apps/web/app/_api/mutations/useUpdateEvaluation.ts
  apps/web/app/_api/queries/evaluation.ts
  apps/web/app/_api/types/evaluation.ts
  apps/web/app/books/[id]/_components/DialogTrigger.tsx
  apps/web/app/books/[id]/_components/KeywordSection.tsx
  apps/web/app/books/[id]/_components/ReadingCard.tsx
  apps/web/app/books/[id]/review/_components/ReviewContent.tsx
  apps/web/app/books/[id]/review/error.tsx
  apps/web/app/books/[id]/review/page.tsx
  apps/web/app/books/_utils/getChipIconUrl.ts
Labels: feat

#103 [CHORE] webp 형식으로 변경
  apps/web/app/_api/queries/book.ts
  apps/web/app/closet/_components/ClosetSecion.tsx
  apps/web/app/home/_components/Home.tsx
  apps/web/app/home/_constants/topbar.ts
  apps/web/app/onboarding/_components/Tutorial.tsx
  apps/web/app/store/page.tsx
  apps/web/public/HOME.png
  apps/web/public/HOME.webp
  apps/web/public/STORE.png
  apps/web/public/STORE.webp
  apps/web/public/TopBar/CLOSET.png
  apps/web/public/TopBar/CLOSET.webp
  apps/web/public/TopBar/MISSION.png
  apps/web/public/TopBar/MISSION.webp
  apps/web/public/TopBar/SHARE.png
  apps/web/public/TopBar/SHARE.webp
  apps/web/public/TopBar/STORE.png
  apps/web/public/TopBar/STORE.webp
  apps/web/public/closet/BG_CLOSET.png
  apps/web/public/closet/BG_CLOSET.webp
  apps/web/public/font/BG_CLOSET.webp
  apps/web/public/onboarding/00.png
  apps/web/public/onboarding/00.webp
  apps/web/public/onboarding/00_BACK.png
  apps/web/public/onboarding/00_BACK.webp
  apps/web/public/onboarding/01.png
  apps/web/public/onboarding/01.webp
  apps/web/public/onboarding/01_05_07_08_BACK.png
  apps/web/public/onboarding/01_05_07_08_BACK.webp
  apps/web/public/onboarding/02.png
  apps/web/public/onboarding/02.webp
  apps/web/public/onboarding/02_03_BACK.png
  apps/web/public/onboarding/02_03_BACK.webp
  apps/web/public/onboarding/03.png
  apps/web/public/onboarding/03.webp
  apps/web/public/onboarding/04.png
  apps/web/public/onboarding/04.webp
  apps/web/public/onboarding/04_06_BACK.png
  apps/web/public/onboarding/04_06_BACK.webp
  apps/web/public/onboarding/05.png
  apps/web/public/onboarding/05.webp
  apps/web/public/onboarding/06.png
  apps/web/public/onboarding/06.webp
  apps/web/public/onboarding/07.png
  apps/web/public/onboarding/07.webp
  apps/web/public/onboarding/08.png
  apps/web/public/onboarding/08.webp
Labels: chore

#104 [FEAT] 책 등록 후 Reward 모달 연결
  apps/web/app/_components/ItemModal.tsx
  apps/web/app/_components/RewardModal.tsx
  apps/web/app/books/[id]/_components/BookStatusModal.tsx
  packages/ui/src/components/Modal/Modal.tsx
Labels: feat

#106 [FEAT] 책 등록 api 요청 dto에 thumbnailUrl 추가
  apps/web/app/_api/types/book.ts
  apps/web/app/books/[id]/_components/BookInfo.tsx
  apps/web/app/books/_components/CardList.tsx
  apps/web/app/search/_components/BookCard.tsx
  apps/web/app/search/_components/BookList.tsx
  apps/web/app/search/_fixture/search.ts
Labels: feat

#107 [FEAT] 책장 전체 조회 api 응답에 totalBookCount 추가
  apps/web/app/_api/types/book.ts
  apps/web/app/books/_components/BookList.tsx
Labels: feat

#110 [FEAT] favicon 설정
  apps/web/app/_api/types/book.ts
  apps/web/app/books/[id]/_components/BookInfo.tsx
  apps/web/app/books/_components/CardList.tsx
  apps/web/app/favicon.ico
  apps/web/app/layout.tsx
  apps/web/app/onboarding/_components/Tutorial.tsx
  apps/web/app/search/_components/BookCard.tsx
  apps/web/app/search/_components/BookList.tsx
  apps/web/public/MAIN.png
Labels: feat

#118 [FEAT] 리뷰 등록 후 보상 모달 추가
  apps/web/app/_components/RewardModal.tsx
  apps/web/app/books/[id]/review/_components/ReviewContent.tsx
  apps/web/app/layout.tsx
  apps/web/app/nickname/page.tsx
Labels: feat

#126 [FEAT] blacky 이미지 webp로 변경
  apps/web/app/_constants/status.ts
  apps/web/app/mission/_components/MissionCardList.tsx
  public/assets/BLACKY_DONE.png
  public/assets/BLACKY_DONE.webp
  public/assets/BLACKY_ING.png
  public/assets/BLACKY_ING.webp
  public/assets/BLACKY_PREV.png
  public/assets/BLACKY_PREV.webp
Labels: feat

#132 [FEAT] ghost 이미지 webp 확장자로 변경
  apps/web/app/_components/ItemModal.tsx
  apps/web/app/books/[id]/_components/BookInfo.tsx
  apps/web/app/books/_components/CardList.tsx
  apps/web/app/closet/_util/image.ts
  apps/web/app/home/_components/Ghost.tsx
  apps/web/app/home/_components/MemberInfo.tsx
  apps/web/app/profile/_components/Profile.tsx
  apps/web/app/search/_components/BookCard.tsx
  apps/web/app/store/_components/ItemBox.tsx
  apps/web/public/Ghost/ANGEL_GHOST.png
  apps/web/public/Ghost/ANGEL_GHOST.webp
  apps/web/public/Ghost/BABY_GHOST.png
  apps/web/public/Ghost/BABY_GHOST.webp
  apps/web/public/Ghost/BAEKDO_CAT_GHOST.png
  apps/web/public/Ghost/BAEKDO_CAT_GHOST.webp
  apps/web/public/Ghost/BASIC_GHOST.png
  apps/web/public/Ghost/BASIC_GHOST.webp
  apps/web/public/Ghost/CAT_GHOST.png
  apps/web/public/Ghost/CAT_GHOST.webp
  apps/web/public/Ghost/CHEESE_CAT_GHOST.png
  apps/web/public/Ghost/CHEESE_CAT_GHOST.webp
  apps/web/public/Ghost/DETECTIVE_GHOST.png
  apps/web/public/Ghost/DETECTIVE_GHOST.webp
  apps/web/public/Ghost/DEVIL_GHOST.png
  apps/web/public/Ghost/DEVIL_GHOST.webp
  apps/web/public/Ghost/DEV_GHOST.png
  apps/web/public/Ghost/DEV_GHOST.webp
  apps/web/public/Ghost/FRANKENSTEIN_GHOST.png
  apps/web/public/Ghost/FRANKENSTEIN_GHOST.webp
  apps/web/public/Ghost/HERO_GHOST.png
  apps/web/public/Ghost/HERO_GHOST.webp
  apps/web/public/Ghost/LADY_GHOST.png
  apps/web/public/Ghost/LADY_GHOST.webp
  apps/web/public/Ghost/LITTLEPRINCE_GHOST.png
  apps/web/public/Ghost/LITTLEPRINCE_GHOST.webp
  apps/web/public/Ghost/MUMMY_GHOST.png
  apps/web/public/Ghost/MUMMY_GHOST.webp
  apps/web/public/Ghost/REDHOOD_GHOST.png
  apps/web/public/Ghost/REDHOOD_GHOST.webp
  apps/web/public/Ghost/SAMURAI_GHOST.png
  apps/web/public/Ghost/SAMURAI_GHOST.webp
  apps/web/public/Ghost/SIAMESE_CAT_GHOST.png
  apps/web/public/Ghost/SIAMESE_CAT_GHOST.webp
  apps/web/public/Ghost/WIZARD_GHOST.png
  apps/web/public/Ghost/WIZARD_GHOST.webp
Labels: feat

#137 [FEAT] 토스트 추가
  apps/web/app/books/[id]/_components/DialogTrigger.tsx
  apps/web/app/books/[id]/review/_components/ReviewContent.tsx
  apps/web/app/closet/_components/ClosetSecion.tsx
  apps/web/app/layout.tsx
  apps/web/app/nickname/page.tsx
  apps/web/app/search/_components/BookList.tsx
  apps/web/app/store/_components/ItemInfo.tsx
  apps/web/package.json
  pnpm-lock.yaml
Labels: feat

#147 [CHORE] 검색 엔진 등록
  apps/web/app/layout.tsx
  apps/web/next-sitemap.config.js
  apps/web/package.json
  apps/web/public/robots.txt
  apps/web/public/sitemap-0.xml
  apps/web/public/sitemap.xml
  pnpm-lock.yaml
Labels: chore
