Repository dnd-side-project/dnd-12th-9-frontend, pull requests merged in 2025-04, with the labels that each got.

#173 [FEAT] 쿼리스트링으로 로그인 이후 리다이렉트 경로 조정
  apps/web/app/_api/acessToken.ts
  apps/web/app/home/page.tsx
  apps/web/app/nickname/page.tsx
  apps/web/app/page.tsx
Labels: feat

#175 [BUGFIX] overflow-scroll 스크롤바 때문에 배경이 잘리는 버그 수정
  apps/web/app/books/_components/Card.tsx
  apps/web/app/books/_components/CardList.tsx
  apps/web/app/search/_components/BookCard.tsx
  packages/ui/src/components/Layout/PageLayout/PageLayout.tsx
Labels: fix

#176 [FEAT] 설정 페이지 퍼블리싱
  apps/web/app/home/_constants/topbar.ts
  apps/web/app/setting/_components/NickNameModal.tsx
  apps/web/app/setting/_components/SettingList.tsx
  apps/web/app/setting/_components/SettingsItem.tsx
  apps/web/app/setting/_page.tsx
Labels: feat

#186 [REFACTOR] Toast 라이브러리 변경, 커스텀 옵션 적용
  .github/workflows/labeler.yaml
  apps/web/app/books/[id]/_components/DialogTrigger.tsx
  apps/web/app/books/[id]/review/_components/ReviewContent.tsx
  apps/web/app/closet/_components/ClosetSecion.tsx
  apps/web/app/layout.tsx
  apps/web/app/nickname/page.tsx
  apps/web/app/profile/_components/Profile.tsx
  apps/web/app/search/_components/BookList.tsx
  apps/web/app/store/_components/ItemInfo.tsx
  apps/web/package.json
  packages/ui/src/components/Header/Header.tsx
  pnpm-lock.yaml
Labels: refactor

#188 [FEAT] Not-Found 페이지 구현
  apps/web/app/not-found.tsx
  apps/web/public/Ghost/SAD_LUNA.webp
Labels: feat

#187 [FEAT] Switch 컴포넌트 구현
  packages/ui/package.json
  packages/ui/src/components/Switch/Switch.tsx
  packages/ui/src/components/Switch/index.ts
  pnpm-lock.yaml
Labels: feat

#190 [REFACTOR] LUNA이미지 motion 적용
  apps/web/app/_components/SadLuna.tsx
  apps/web/app/not-found.tsx
  apps/web/public/Ghost/SAD_LUNA_NOTEARS.webp
  apps/web/public/Ghost/TEARS.webp
Labels: refactor

#192 [CHORE] 의존성을 catalog를 이용해 한 곳에서 관리
  apps/storybook/package.json
  apps/web/app/_components/SadLuna.tsx
  apps/web/app/assets/LoginMotion.tsx
  apps/web/app/home/_components/Ghost.tsx
  apps/web/app/onboarding/_components/Motion.tsx
  apps/web/app/store/_components/ItemBox.tsx
  apps/web/package.json
  package.json
  packages/eslint-config/package.json
  packages/tailwind-config/package.json
  packages/ui/package.json
  packages/ui/src/components/Drawer/Drawer.tsx
  packages/ui/src/components/Modal/Modal.tsx
  packages/ui/src/components/Portal/Portal.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: chore

#193 [BUGFIX] 꾸미기 페이지에서 저장버튼 하단에 고정
  apps/web/app/closet/_components/ClosetSecion.tsx
  packages/ui/src/components/Button/Button.tsx
Labels: fix
